GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmtrdSIsImlkIjoiNjkwY2E4YjlkYjFmYjJjYzkyZDljMDA2IiwiaWF0IjoxNzYyNDM4NDM4LCJleHAiOjE3NjI0NDIwMzh9.ElRexwqIZiTWpyYEgBuYmuCVegAoQXe4sRFKn60F4yI
